-- Generated by scripts/gen-seed.mjs. Vendors + contracts + network vendor backfill only.
-- Apply to a database already seeded with operators, properties, and assets.
begin;

do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Comcast Business', 'ISP', 'Monthly', NULL, '1-800-391-3000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://business.comcast.com', 'https://business.comcast.com/support', 'https://login.comcast.net', 'Cartersville acct 8220210501095543: ISP $309.95 (cbc-cart-isp) + Voice $134.95 (cbc-cart-voice) = $444.90/mo. Norcross (8220133050478318, $505.85/mo ISP+TV). Jefferson (708900956, $417.25/mo Ethernet Dedicated). Rome (8220160110667101, $347.51/mo ISP+Voice, ⚠️ past due). Total est. MRC: $1,715.51/mo.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-cartersville'), 'Internet — Cartersville (Comcast Gigabit Extra bundle)', '8220210501095543', NULL, NULL, '309.95', 'OID-0012407729. ISP portion of bundle: Internet Gigabit Extra $240 + Connection Pro $20 + Equip $10 + Battery $10 + Static IP $29.95 = $309.95/mo pre-tax. 24-month term. Annmarie Pasmore (770)548-6638 anne@highlands.care.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-cartersville'), 'Voice — Cartersville (5 Comcast Mobility Lines)', '8220210501095543', NULL, NULL, '134.95', 'OID-0012407729. Voice portion: 4 additional Mobility Lines $100 + Equipment Fee $34.95 = $134.95/mo pre-tax. 5 total lines: (770)606-1141, (470)227-7954, (770)382-8989, (770)386-7847, (470)315-4320. $26.99/line avg. Caller ID: Felton Manor. Samsung digital phones on legacy Comcast switch.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-rome'), 'Internet — Rome (Comcast Advanced + Static IP-5)', '8220160110667101', NULL, NULL, '207.90', 'Rome ISP portion. Invoice 8220160110667101 Apr 2026. Bundled Internet Advanced+SecurityEdge: $294 - $154 discount + equip $27.95 = $167.95. Static IP-5: $39.95. Total ISP: $207.90/mo pre-tax. Attn: Joy Hope. ⚠️ PAST DUE $332.64 — late fee $15.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-rome'), 'Voice — Rome (4 Comcast Mobility Lines)', '8220160110667101', NULL, NULL, '97.00', 'Rome voice portion. 3 Mobility Lines $75.00 (3×$25 after bundle discount) + Service fees $22.00 (Directory Listing Mgmt $11 + Voice Network Investment $11) = $97.00/mo. 4 lines: (706)802-0541, (706)232-8661, (706)204-7093, (706)232-8662. $24.25/line avg. Samsung digital phones on legacy Comcast switch.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-norcross'), 'Internet — Norcross (Comcast Business Advanced + Static IP)', '8220133050478318', NULL, NULL, '207.90', 'Norcross ISP portion. Invoice 8220133050478318 May 2026. Data+SecurityEdge: $279 - $134 discount = $145 net + Static IP $34.95 + equip $27.95 = $207.90/mo pre-tax. Billing: Highlands Norcross SL LLC, Attn Ramesh Ramchandran. Support 470-489-2100.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-norcross'), 'TV — Norcross (Comcast Business TV)', '8220133050478318', NULL, NULL, '276.45', 'Norcross TV portion. Invoice 8220133050478318 May 2026. TV Standard $124.95 + Sports+Entertainment $34.95 + TV Box+Remote $11.95 + 4×additional boxes $47.80 + 1×TV Adapter $11.95 + Broadcast TV Fee $40.15 + Regional Sports Fee $4.70 = $276.45/mo. Note: FanDuel Sports Network no longer available as of May 7 2026.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-jefferson'), 'Internet Dedicated — Jefferson (Ethernet 1Gbps/100Mbps)', '708900956', NULL, NULL, '417.25', 'Comcast Business Ethernet Dedicated Internet. Acct 708900956, Invoice 001004142546 May 2026. Port 1Gbps, Basic Bandwidth 100Mbps. Circuit ID: 30.VLXP.114407..CBCL.. Port ID: 30.KRGS.092864..CBCL.. Monthly $399.95 + taxes $17.30 = $417.25. ⚠️ PAST DUE as of May 2026 invoice — previous balance $429.11 unpaid.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'AT&T', 'ISP', 'Monthly', NULL, '1-800-288-2020', NULL, '337883844', NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.att.com/smallbusiness/', 'https://www.att.com/support/', 'https://www.att.com/my/#/', 'Columbia acct 337883844. Also ISP for Gaston (separate acct). AutoPay set up Apr 2026.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-columbia'), 'Internet + Phone — Columbia', '337883844', NULL, NULL, '274.67', 'Internet 25 $110/mo + Static IP $30/mo + fees = $149.80/mo. 3 phone lines $30/ea + fees = $124.87/mo. Total $274.67/mo. Late payment Apr 2026 — AutoPay enabled.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-gaston'), 'Internet 50 + Phone — Gaston', '151834264', NULL, NULL, '146.26', 'AT&T Gaston — Highlands Senior Living. Acct 151834264, Sep 2025. Internet 50 $60 + $4.20 fee = $64.20. Phone: (803)955-0453 unlimited $30 + (803)755-8333 $30 + fees $22.06 = $82.06. Total $146.26/mo. AutoPay bank acct, Oct 19.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-gaston'), 'AT&T Wireless — Gaston (Rapha)', '287319845202', NULL, NULL, '44.00', 'AT&T Mobility. Acct 287319845202, Foundation Acct 61488640, Sep 2025. Billing: Rapha Residential Care, 3959 Fish Hatchery Rd, Gaston SC 29053. 1 line: (803)908-7087, Mobile Select 1GB Pool Smartphone $35 + fees/taxes $9 = $44/mo. AutoPay bank, Oct 20.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Starlink', 'ISP', 'Monthly', 'Ramesh Ram', NULL, 'support@starlink.com', 'ACC-6553933-40065-14', NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.starlink.com', 'https://support.starlink.com', 'https://www.starlink.com/account', 'ISP: Forest City (primary, Residential Max $120/mo, acct ACC-6553933-40065-14). Jefferson (backup WAN, no separate invoice).')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-forestcity'), 'Starlink Residential Max — Forest City', 'ACC-6553933-40065-14', NULL, NULL, '120.00', 'Residential Max plan $120/mo. Invoice INV-DF-US-VV7HN437JMCAD9YYM8 May 2026. Kit serial KIT402564062XSF. Contact: Ramesh Ram, 2270 Oakland Rd, Forest City NC 28043.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'GoTo', 'VoIP', 'Monthly', NULL, '1-888-646-0014', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.goto.com', 'https://support.goto.com', 'https://admin.goto.com', 'SIP phones: Jefferson (CN-6434073-2508, $184.58/mo, 9 seats), Gaston (CN-6646742-2511, $173.74/mo, 8 seats), Rome (CN-928065-2101, $153.43/mo, 6 seats), Forest City (est. ~$65/mo, 3 seats). $18/seat + fees.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-jefferson'), 'GoTo Voice — Jefferson', 'CN-6434073-2508', NULL, NULL, '184.58', '9 seats × $18.00 + fees. Invoice IN7105370066 May 2026.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-gaston'), 'GoTo Voice — Gaston', 'CN-6646742-2511', NULL, NULL, '173.74', '8 seats × $18.00 + fees. Invoice IN7105361191 May 2026.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-rome'), 'GoTo Voice — Rome', 'CN-928065-2101', NULL, NULL, '153.43', '6 seats × $18.00 + fees + $26.25 equipment rental. Invoice IN7105333077 May 2026.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-forestcity'), 'GoTo Voice — Forest City', NULL, NULL, NULL, '65.16', '3 seats est. × $21.72 (Gaston rate basis). Account number TBD.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), '8x8', 'VoIP', 'Monthly', NULL, '1-888-898-8733', NULL, 'QB0507013010319', NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.8x8.com', 'https://support.8x8.com', 'https://sso.8x8.com/v2/login', 'SIP phones: Norcross (The Landings). Acct QB0507013010319, $245.04/mo. Invoice 9866592 May 2026. 9× X1 + 1× X2 + Polycom VVX 411 devices. AutoPay.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-norcross'), '8x8 VoIP — Norcross', 'QB0507013010319', NULL, NULL, '245.04', 'Invoice 9866592, May 2026. 9× X Series X1 $15/ea + 1× X2 $25 + DIDs + taxes $45.08. 9× Polycom VVX 411 (no device charge). Account: The Landings at Norcross. AutoPay Mastercard ****2529.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Cisco Meraki', 'Network Vendor', '3-Year Subscription', NULL, '1-800-553-6387', NULL, NULL, '2024-05-21', '2027-06-20', '2027-06-20', NULL, 30, '⚠️ RENEWAL DUE JUNE 2027 — $8,941.98 LUMP SUM. ALL MERAKI DEVICES (Jefferson + Norcross) GO OFFLINE WITHOUT RENEWAL. Tazergy Invoice 121831.', 'https://meraki.cisco.com', 'https://documentation.meraki.com', 'https://n219.dashboard.meraki.com/login/', '⚠️ RANSOM-WARE SUBSCRIPTION MODEL — ALL MANAGED HARDWARE GOES OFFLINE IF LICENSE LAPSES. Jefferson: 30 devices (MX67+5 switches+24 APs) $234.97/mo amortized, $8,942 lump due Jun 2027. Norcross: 2 devices $27.61/mo est. Procured via Tazergy Invoice 121831.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-jefferson'), 'Meraki 3yr License — Jefferson (MX67 + 2×MS120-24P + 3×MS120-8FP + 24×MR33)', 'Z28R-JRJP-WJ43', '2024-05-21', '2027-06-20', '234.97', '⚠️ LUMP SUM $8,356.98 + $585 tax = $8,941.98 due June 2027. MX67 $24.82/mo + 2×MS120-24P $12.42/mo + 3×MS120-8FP $8.37/mo + 24×MR33 $189.36/mo = $234.97/mo amortized. Tazergy Invoice 121831 May 2024.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-norcross'), 'Meraki 3yr License — Norcross (MX67 + 1×MS120-8FP) — est. (1 Meraki switch only; other switches are Brocade and Araknis)', 'Z28R-JRJP-WJ43', '2024-05-21', '2027-06-20', '27.61', 'Estimated same rate as Jefferson for current term. MX67 $24.82/mo + MS120-8FP $2.79/mo = $27.61/mo amortized. WARNING: renewal rate unknown — Meraki pricing increases each cycle. Previous term est. ~$994 but expect significantly higher. Budget accordingly.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Ubiquiti', 'Network Vendor', 'Per Purchase', NULL, NULL, 'support@ui.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.ui.com', 'https://help.ui.com', 'https://unifi.ui.com', 'APs: Cartersville (AP AC PRO x6), Rome (U6+ x8). Router: Rome (UDM Pro). Controller: Cartersville (UCK G2+). Hardware purchases only, no subscription.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Ruckus / CommScope', 'Network Vendor', 'Monthly', NULL, '1-855-782-5871', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.ruckusnetworks.com', 'https://support.ruckuswireless.com', NULL, 'APs: Norcross (R510x10, R610x1, R650x1). Controller hosted by Tazergy.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'TP-Link', 'Network Vendor', 'Per Purchase', NULL, '1-866-225-8139', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.tp-link.com', 'https://www.tp-link.com/us/support/', 'https://omada.tplinkcloud.com', 'Deco APs: Gaston (AXE5400 x7), Forest City (M8 x6). Hardware purchases only.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Netgear', 'Network Vendor', 'Per Purchase', NULL, '1-888-638-4327', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.netgear.com', 'https://www.netgear.com/support/', NULL, 'Switches at Gaston, Jefferson, Forest City, Rome, Cartersville. Hardware purchases only.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Tazergy', 'Network MSP', 'Monthly + Per Service Call', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.tazergy.com', 'https://www.tazergy.com/support', NULL, 'Managed MSP: Norcross + Jefferson. $300/mo each = $600/mo MRC. Plus per-service-call charges for on-site visits.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-norcross'), 'Managed WiFi + Ruckus controller hosting', NULL, NULL, NULL, '300', '$300/mo flat. Ruckus controller hosted by Tazergy. Per-site MSP contract.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-jefferson'), 'Managed network services', NULL, NULL, NULL, '300', '$300/mo flat. Per-site MSP contract.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, NULL, 'On-site service calls', NULL, NULL, NULL, NULL, 'Billed per service call when Tazergy staff visit on-site. Rate TBD — add to contract when known.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Dell Technologies', 'Hardware', 'Per Purchase', NULL, '1-877-275-3355', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.dell.com/en-us/shop/scc/sc/business', 'https://www.dell.com/support/home/en-us', 'https://www.dell.com/support/my-account/en-us', 'PCs: Latitude 5420/7420/7480, Optiplex 7490 AIO across multiple locations.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'HP', 'Hardware', 'Per Purchase', NULL, '1-800-474-6836', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.hp.com/us-en/shop/vwa/hp-products', 'https://support.hp.com/us-en', 'https://support.hp.com/us-en/myproducts', 'PCs: EliteBook 840 G6, Elite Book Pro. Norcross, Forest City, Remote.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Yealink', 'Hardware', 'Per Purchase', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.yealink.com', 'https://support.yealink.com', NULL, 'SIP phones: Jefferson (SIP-T34W x8), Gaston (x7), Forest City (x2), Rome (x1 unactivated).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Poly / Plantronics', 'Hardware', 'Per Purchase', NULL, '1-800-765-9750', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.poly.com', 'https://www.poly.com/us/en/support', NULL, 'Phones: Norcross (VVX 411 x8), Rome (VVX 450 x5). ATA: Forest City (ATA 400 fax).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Grandstream', 'Hardware', 'Per Purchase', NULL, '1-626-666-6242', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.grandstream.com', 'https://www.grandstream.com/support', NULL, 'ATA/Fax: Gaston (HT801 GoTo fax).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Obihai / Polycom', 'Hardware', 'Per Purchase', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.obihai.com', 'https://www.obihai.com/support', NULL, 'ATA: Norcross 8x8 fax (OBi 300 SIP ATA + OBi Handset, ext 100).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Cisco', 'Hardware', 'Per Purchase', NULL, '1-800-553-6387', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.cisco.com', 'https://www.cisco.com/c/en/us/support/index.html', NULL, 'ATA: Jefferson GoTo fax line (ATA191, ext 1008).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Retirement Home TV', 'TV / Entertainment', 'Monthly', NULL, '(877) 477-3474', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.retirementhometv.com', 'https://www.retirementhometv.com/support', 'https://www.retirementhometv.com', 'TV service: Rome (acct 1-111112001, $998.56/mo) and Cartersville (acct 2346805, $494.50/mo). Total: $1,493.06/mo. Phone: (877) 477-3474. RetirementHomeTV Corporation, 4604 Arden Dr, Fort Wayne IN 46804.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-rome'), 'RetirementHomeTV — Rome', '1-111112001', NULL, NULL, '998.56', 'Invoice 272855, May 1 2026. Monthly $964.31 + GA Sales Tax Floyd Co $34.25. Billed to: Highlands Rome, P.O. Box 2568, Hickory NC 28603. Due upon receipt.');
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-cartersville'), 'RetirementHomeTV — Cartersville', '2346805', NULL, NULL, '494.50', 'Invoice 272925, May 1 2026. Monthly $487.45 + GA Sales Tax Bartow Co $7.05. Billed to: Highlands Senior Care, 16 Roving Rd, Cartersville GA 30121. Net 15.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Allbridge', 'TV / Entertainment', 'Monthly', NULL, '(866) 734-4976', 'accountsreceivable@allbridge.com', 'C127140', NULL, NULL, NULL, NULL, NULL, NULL, 'https://allbridge.com', 'https://allbridge.com/support/', 'https://skyadmin.io/pay', 'TV service: Jefferson (Jackson Oaks Senior Living). Customer ID C127140. Pay online: skyadmin.io/pay. Accts receivable: accountsreceivable@allbridge.com. NOTE: Past due balance flagged Jan 2024 — verify current payment status.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-jefferson'), 'Allbridge Video Services — Jefferson', 'C127140', NULL, NULL, '1068.53', 'Allbridge Video Services $1,064.85 + tax $3.68 = $1,068.53/mo recurring. Invoice 20442462 Jan 2024. Note: account had past-due balance $2,451.40 as of Jan 2024 — confirm current status.');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Comcast TV — Norcross', 'TV / Entertainment', 'Monthly', NULL, '1-800-391-3000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://business.comcast.com', 'https://business.comcast.com/support', 'https://login.comcast.net', 'TV: Norcross. Possibly Jefferson also (unconfirmed).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Comsec', 'Camera / Security', 'Monthly', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '28 analog cameras: Cartersville. DVR controller: LTS LTD8432K-ST (supplied by LTS Security).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Ring / Amazon', 'Camera / Security', 'Monthly', NULL, '1-800-656-1918', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://ring.com', 'https://support.ring.com', 'https://account.ring.com', 'Ring cameras: Rome (4), Jefferson, Norcross.')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'Streaming cameras', 'Camera / Security', 'Monthly', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Streaming cameras: Gaston, Forest City (vendor TBD).')
  returning id into vid;
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'T-Mobile Business', 'Mobile / Wireless', 'Monthly', NULL, '1-800-375-1126', NULL, '987665350', NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.t-mobile.com/business', 'https://www.t-mobile.com/support', 'https://account.t-mobile.com', 'Mobile: Cartersville/corporate lines. Acct 987665350. 6 lines — 4 Bus Unl Select Promo + 2 AAL (Galaxy S25 Icy Blue + Navy). AutoPay. Late fee Jan 2026 — verify.')
  returning id into vid;
  insert into public.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)
  values (vid, (select id from public.properties where slug = 'loc-cartersville'), 'T-Mobile Business Mobile — Cartersville/Corporate', '987665350', NULL, NULL, '218.78', '6 lines: 4× Bus Unl Select Promo $120 + 2× AAL $30 each. Billing addr: 575 Laurel Oaks Ln, Alpharetta GA 30004. Invoice 987665350-39 Mar 2026 $229.72 (incl $10.94 late fee). Recurring: ~$218.78/mo. 2× Galaxy S25 on EIP ($566.61 balance each, installment 7/24).');
end $seed$;
do $seed$
declare vid uuid;
begin
  insert into public.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)
  values ((select id from public.operators limit 1), 'LTS Security', 'Camera / Security', 'Per Purchase', NULL, '1-888-813-8388', 'support@ltssecurity.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://www.ltssecurity.com', 'https://www.ltssecurity.com/support', NULL, 'Analog DVR system: Cartersville. LTD8432K-ST DVR + 28 analog cameras.')
  returning id into vid;
end $seed$;
update public.asset_networks an set vendor_id = v.id
from public.vendors v where an.vendor is not null and lower(an.vendor) = lower(v.name);

commit;
