// Generates supabase/seed.sql from the prototype's SEED_* arrays in ITAssetTrack.jsx.
// Run: node scripts/gen-seed.mjs
// Phase 1 seeds operators, properties, and assets of type computer/software/ata/
// camera/network. Phone assets are skipped (deferred to Phase 2). Asset type is
// derived from category, which is more reliable than the prototype's `type` field.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = readFileSync(join(root, 'ITAssetTrack.jsx'), 'utf8')

// Pull a `const NAME = [ ... ]` array literal out of the source and evaluate it.
// The arrays contain only string/number/array/object literals, so eval is safe here.
function extractArray(name) {
  const start = src.indexOf(`const ${name}`)
  if (start === -1) throw new Error(`${name} not found`)
  const open = src.indexOf('[', start)
  let depth = 0
  for (let i = open; i < src.length; i++) {
    const ch = src[i]
    if (ch === '[') depth++
    else if (ch === ']') {
      depth--
      if (depth === 0) {
        const literal = src.slice(open, i + 1)
        return new Function(`return (${literal})`)()
      }
    }
  }
  throw new Error(`Unbalanced brackets for ${name}`)
}

const OPS = extractArray('SEED_OPS')
const LOCS = extractArray('SEED_LOCS')
const ASSETS = extractArray('SEED_ASSETS')
const NET = extractArray('SEED_NET_ASSETS')
const VENDORS = extractArray('SEED_VENDORS')
const NETSUM = extractArray('NETWORK_SUMMARY')

const CATEGORIES = new Set([
  'Laptop', 'Desktop', 'Software License', 'ATA / Fax', 'Security Camera',
  'DVR / NVR Controller', 'Router / Firewall', 'Switch', 'Access Point',
  'Network Controller', 'Server', 'Printer', 'Monitor', 'UPS', 'Other',
])
const STATUSES = new Set([
  'Active', 'Inactive', 'In Repair', 'Disposed', 'Spare', 'Needs Attention',
])
const WIFI = new Set(['WiFi 5', 'WiFi 6', 'WiFi 6E', 'WiFi 5/6'])
const NETWORK_CATS = new Set([
  'Router / Firewall', 'Switch', 'Access Point', 'Network Controller',
  'Server', 'DVR / NVR Controller',
])

// SQL literal: empty/missing -> NULL, otherwise single-quote-escaped text.
function s(v) {
  if (v === undefined || v === null || String(v).trim() === '') return 'NULL'
  return `'${String(v).replace(/'/g, "''")}'`
}
function intLit(v) {
  const n = parseInt(v, 10)
  return Number.isNaN(n) ? 'NULL' : String(n)
}
function pick(set, v) {
  return set.has(v) ? s(v) : 'NULL'
}
const OPERATOR = '(select id from it_asset_tracker.operators limit 1)'
function propRef(locId) {
  return locId ? `(select id from it_asset_tracker.properties where slug = ${s(locId)})` : 'NULL'
}

function normalizeCategory(cat) {
  if (CATEGORIES.has(cat)) return cat
  if (cat === 'ATA / VoIP Appliance') return 'ATA / Fax'
  return 'Other'
}

// Derive the asset_type enum value from the (normalized) category.
function deriveType(category, fromNetArray) {
  if (fromNetArray) return 'network'
  if (category === 'Software License') return 'software'
  if (category === 'ATA / Fax') return 'ata'
  if (category === 'Security Camera') return 'camera'
  if (category === 'Laptop' || category === 'Desktop') return 'computer'
  if (NETWORK_CATS.has(category)) return 'network'
  return 'computer' // Printer/Monitor/UPS/Other fall back to a base computer row
}

const out = []
out.push('-- Generated by scripts/gen-seed.mjs from ITAssetTrack.jsx. Do not edit by hand.')
out.push('-- Phase 1 seed: operators, properties, and non-phone assets.')
out.push('begin;')
out.push('')

// Operator + contacts
const op = OPS[0]
out.push('insert into it_asset_tracker.operators (name, short_name, logo_url, web_link, street, city, state, zip, country) values (')
out.push(`  ${s(op.name)}, ${s(op.shortName)}, ${s(op.logo)}, ${s(op.webLink)}, ${s(op.street)}, ${s(op.city)}, ${s(op.state)}, ${s(op.zip)}, ${s(op.country)}`)
out.push(');')
for (const c of op.contacts || []) {
  out.push(`insert into it_asset_tracker.operator_contacts (operator_id, name, title, phone, email) values (${OPERATOR}, ${s(c.name)}, ${s(c.title)}, ${s(c.phone)}, ${s(c.email)});`)
}
out.push('')

// Properties
for (const l of LOCS) {
  out.push('insert into it_asset_tracker.properties (operator_id, slug, name, short_name, address, main_phone, ed_name, maintenance_tech, notes) values (')
  out.push(`  ${OPERATOR}, ${s(l.id)}, ${s(l.name)}, ${s(l.shortName)}, ${s(l.address)}, ${s(l.mainPhone)}, ${s(l.edName)}, ${s(l.maintenanceTech)}, ${s(l.notes)}`)
  out.push(');')
}
out.push('')

// Phone helpers. line_status keeps the prototype vocabulary; a stray "Active"
// is normalized to "Activated". The base asset status is derived from it.
function phoneLineStatus(v) {
  return v === 'Active' ? 'Activated' : v || ''
}
function phoneAssetStatus(lineStatus) {
  if (lineStatus === 'Ready' || lineStatus === 'Activated') return 'Active'
  if (lineStatus === 'Needs Attention') return 'Needs Attention'
  if (['Unavailable', 'Offline', 'Unregistered'].includes(lineStatus)) return 'Inactive'
  return 'Active'
}
function phoneCategory(lineType) {
  const map = {
    'Desk phone': 'Desk Phone',
    'Analog telephone adapter': 'ATA / Fax',
    Analog: 'Analog Line',
    Mobile: 'Mobile',
    Softphone: 'Softphone',
    'Conference room': 'Conference Phone',
    'Ring group': 'Other',
    'Overhead paging': 'Other',
    'Virtual fax': 'ATA / Fax',
  }
  return map[lineType] || 'Other'
}

// Phone DO blocks are emitted separately so they can also be applied on their
// own to an already-seeded database (supabase/seed_phones.sql).
const phoneOut = []

// Assets
const all = ASSETS.map((a) => ({ a, net: false })).concat(NET.map((a) => ({ a, net: true })))
const counts = { computer: 0, software: 0, ata: 0, camera: 0, network: 0, phone: 0, dids: 0, vendors: 0, contracts: 0, networkSummaries: 0 }

for (const { a, net } of all) {
  if (a.type === 'Phone') {
    counts.phone++
    const lineStatus = phoneLineStatus(a.status)
    const category = phoneCategory(a.lineType)
    phoneOut.push('do $seed$')
    phoneOut.push('declare pid uuid;')
    phoneOut.push('begin')
    phoneOut.push('  insert into it_asset_tracker.assets (type, operator_id, property_id, sub_location, category, status, make, model, mac_address, notes)')
    phoneOut.push(`  values ('phone', ${OPERATOR}, ${propRef(a.location)}, ${s(a.subLocation)}, ${s(category)}, ${s(phoneAssetStatus(lineStatus))}, ${s(a.make)}, ${s(a.model)}, ${s(a.macAddress)}, ${s(a.notes)})`)
    phoneOut.push('  returning id into pid;')
    phoneOut.push('  insert into it_asset_tracker.asset_phones (asset_id, provider, extension, public_ip, private_ip, line_type, line_status, last_provisioned, route_to, carrier, activation_code, avg_monthly_cost, cost_type, mrc_notes)')
    phoneOut.push(`  values (pid, ${s(a.provider)}, ${s(a.extension)}, ${s(a.publicIp)}, ${s(a.privateIp)}, ${s(a.lineType)}, ${s(lineStatus)}, ${s(a.lastProvisioned)}, ${s(a.routeTo)}, ${s(a.carrier)}, ${s(a.activationCode)}, ${s(a.avgMonthlyCost)}, ${s(a.costType)}, ${s(a.mrcNotes)});`)
    for (const d of a.dids || []) {
      counts.dids++
      phoneOut.push('  insert into it_asset_tracker.dids (phone_asset_id, number, assigned_to, provider, number_source, number_type, caller_id_name, monthly_rate, notes)')
      phoneOut.push(`  values (pid, ${s(d.number)}, ${s(d.assignedTo)}, ${s(a.provider)}, ${s(d.numberSource)}, ${s(d.numberType)}, ${s(d.externalCallerId)}, ${s(d.avgMonthlyCost)}, ${s(d.mrcNotes)});`)
    }
    phoneOut.push('end $seed$;')
    continue
  }

  const category = normalizeCategory(a.category)
  const type = deriveType(category, net)
  counts[type]++
  const status = STATUSES.has(a.status) ? a.status : 'Active'

  const baseCols = 'type, operator_id, property_id, sub_location, category, status, make, model, serial, hostname, mac_address, ip_address, assigned_user, notes, entry_date, last_seen_on_site'
  const baseVals = [
    s(type), OPERATOR, propRef(a.location), s(a.subLocation), s(category), s(status),
    s(a.make), s(a.model), s(a.serial), s(a.hostname), s(a.macAddress), s(a.ipAddress),
    s(a.assignedUser), s(a.notes), s(a.entryDate), s(a.lastSeenOnSite),
  ].join(', ')

  if (type === 'computer') {
    out.push(`with a as (insert into it_asset_tracker.assets (${baseCols}) values (${baseVals}) returning id)`)
    out.push('insert into it_asset_tracker.asset_computers (asset_id, os_version, os_product_key, product_id, office_version, office_product_key, software_source, processor, ram, storage, graphics, system_type, device_id)')
    out.push(`select id, ${s(a.osVersion)}, ${s(a.osProductKey)}, ${s(a.productId)}, ${s(a.officeVersion)}, ${s(a.officeProductKey)}, ${s(a.softwareSource)}, ${s(a.processor)}, ${s(a.ram)}, ${s(a.storage)}, ${s(a.graphics)}, ${s(a.systemType)}, ${s(a.deviceId)} from a;`)
  } else if (type === 'software') {
    out.push(`with a as (insert into it_asset_tracker.assets (${baseCols}) values (${baseVals}) returning id)`)
    out.push('insert into it_asset_tracker.asset_software (asset_id, office_version, office_product_key, software_source)')
    out.push(`select id, ${s(a.officeVersion)}, ${s(a.officeProductKey)}, ${s(a.softwareSource)} from a;`)
  } else if (type === 'network') {
    out.push(`with a as (insert into it_asset_tracker.assets (${baseCols}) values (${baseVals}) returning id)`)
    out.push('insert into it_asset_tracker.asset_networks (asset_id, isp, port_count, managed, poe, vlan, wifi_standard, admin_ssid, resident_ssid, firmware_version, license_key, renewal_date, vendor, warranty_expiry, purchase_date)')
    out.push(`select id, ${s(a.isp)}, ${intLit(a.portCount)}, ${pick(new Set(['Managed', 'Unmanaged']), a.managed)}, ${pick(new Set(['Yes', 'No']), a.poe)}, ${s(a.vlan)}, ${pick(WIFI, a.wifiStandard)}, ${s(a.adminSsid)}, ${s(a.residentSsid)}, ${s(a.firmwareVersion)}, ${s(a.licenseKey)}, ${s(a.renewalDate)}, ${s(a.vendor)}, ${s(a.warrantyExpiry)}, ${s(a.purchaseDate)} from a;`)
  } else {
    // ata and camera: base row only, no detail table.
    out.push(`insert into it_asset_tracker.assets (${baseCols}) values (${baseVals});`)
  }
}

// Vendors + contracts. A contract's location is a prototype slug (loc-*), a
// property name ("Jefferson"), or operator-wide ("All sites" -> null property).
function contractProp(locId) {
  if (!locId) return 'NULL'
  const v = locId.toLowerCase().trim()
  if (v.startsWith('loc-')) return `(select id from it_asset_tracker.properties where slug = ${s(locId)})`
  const loc = LOCS.find(
    (l) => (l.name || '').toLowerCase() === v || (l.shortName || '').toLowerCase() === v
  )
  return loc ? `(select id from it_asset_tracker.properties where slug = ${s(loc.id)})` : 'NULL'
}

const vendorOut = []
for (const v of VENDORS) {
  counts.vendors++
  vendorOut.push('do $seed$')
  vendorOut.push('declare vid uuid;')
  vendorOut.push('begin')
  vendorOut.push('  insert into it_asset_tracker.vendors (operator_id, name, category, billing_cadence, contact_name, phone, email, account_number, contract_start, contract_expiry, renewal_date, renewal_amount, license_count, renewal_notes, url_website, url_support, url_portal, notes)')
  vendorOut.push(`  values (${OPERATOR}, ${s(v.name)}, ${s(v.category)}, ${s(v.billingCadence)}, ${s(v.contactName)}, ${s(v.phone)}, ${s(v.email)}, ${s(v.accountNumber)}, ${s(v.contractStart)}, ${s(v.contractExpiry)}, ${s(v.renewalDate)}, ${s(v.renewalAmount)}, ${intLit(v.licenseCount)}, ${s(v.renewalNotes)}, ${s(v.urlWebsite)}, ${s(v.urlSupport)}, ${s(v.urlPortal)}, ${s(v.notes)})`)
  vendorOut.push('  returning id into vid;')
  for (const c of v.contracts || []) {
    counts.contracts++
    vendorOut.push('  insert into it_asset_tracker.vendor_contracts (vendor_id, property_id, description, account_number, start_date, end_date, monthly_amount, notes)')
    vendorOut.push(`  values (vid, ${contractProp(c.locationId)}, ${s(c.description)}, ${s(c.accountNumber)}, ${s(c.startDate)}, ${s(c.endDate)}, ${s(c.monthlyAmount)}, ${s(c.notes)});`)
  }
  vendorOut.push('end $seed$;')
}
// Backfill network device vendor links by exact (case-insensitive) name match.
// Unmatched values (Araknis, Comcast) keep their free-text vendor as a fallback.
vendorOut.push('update it_asset_tracker.asset_networks an set vendor_id = v.id')
vendorOut.push('from it_asset_tracker.vendors v where an.vendor is not null and lower(an.vendor) = lower(v.name);')

// Per-property network summaries (one row per property, matched by slug).
const netOut = []
for (const n of NETSUM) {
  counts.networkSummaries++
  netOut.push('insert into it_asset_tracker.network_summaries (property_id, isp, isp_plan, isp_account_number, isp_monthly_cost, router, appliance, switches, switch_models, aps, ap_make, ap_model, wifi_standard, admin_ssid, resident_ssid, phone_system, cameras, tv, tv_account, tv_monthly_cost, notes)')
  netOut.push(`select id, ${s(n.isp)}, ${s(n.ispPlan)}, ${s(n.ispAccountNumber)}, ${s(n.ispMonthlyCost)}, ${s(n.router)}, ${s(n.appliance)}, ${intLit(n.switches)}, ${s(n.switchModels)}, ${intLit(n.aps)}, ${s(n.apMake)}, ${s(n.apModel)}, ${s(n.wifiStandard)}, ${s(n.adminSsid)}, ${s(n.residentSsid)}, ${s(n.phoneSystem)}, ${s(n.cameras)}, ${s(n.tv)}, ${s(n.tvAccount)}, ${s(n.tvMonthlyCost)}, ${s(n.notes)} from it_asset_tracker.properties where slug = ${s(n.location)};`)
}

// Full canonical seed (fresh resets): everything plus phones, vendors, summaries.
const full = out.concat([''], phoneOut, [''], vendorOut, [''], netOut, ['', 'commit;'])
writeFileSync(join(root, 'supabase', 'seed.sql'), full.join('\n') + '\n')

// Network-summaries-only delta (apply to an already-seeded database).
const netFile = [
  '-- Generated by scripts/gen-seed.mjs. Per-property network summaries only.',
  '-- Apply to a database already seeded with properties.',
  'begin;',
  '',
  ...netOut,
  '',
  'commit;',
]
writeFileSync(join(root, 'supabase', 'seed_network.sql'), netFile.join('\n') + '\n')

// Vendors-only delta (apply to an already-seeded database).
const vendorsFile = [
  '-- Generated by scripts/gen-seed.mjs. Vendors + contracts + network vendor backfill only.',
  '-- Apply to a database already seeded with operators, properties, and assets.',
  'begin;',
  '',
  ...vendorOut,
  '',
  'commit;',
]
writeFileSync(join(root, 'supabase', 'seed_vendors.sql'), vendorsFile.join('\n') + '\n')

// Phones-only delta (apply to an already-seeded database).
const phonesFile = [
  '-- Generated by scripts/gen-seed.mjs. Phone assets + DIDs only.',
  '-- Apply to a database already seeded with operators, properties, and non-phone assets.',
  'begin;',
  '',
  ...phoneOut,
  '',
  'commit;',
]
writeFileSync(join(root, 'supabase', 'seed_phones.sql'), phonesFile.join('\n') + '\n')

console.error('Seed generated. Counts:', JSON.stringify(counts))
console.error('Properties:', LOCS.length, 'Operator contacts:', (op.contacts || []).length)
